local _M = {}

_M.DEV_HEALTH_ONLINE = 1
_M.DEV_HEALTH_OFFLINE = 2
_M.DEV_HEALTH_SICK = 3

_M.DEV_TYPE_ATE = 1
_M.DEV_TYPE_NEWFAN = 2
_M.DEV_TYPE_AIRCOND = 3

_M.ALARM_XLW1 = 1
_M.ALARM_XLW2 = 2
_M.ALARM_SPE1 = 3
_M.ALARM_SPE2 = 4

return _M
